"""Tests for CalendarEntry and TravelCalendarEntry models."""

import pytest
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from calendar_tz.models import (
    CalendarEntry,
    TravelCalendarEntry,
    Attendee,
    EventStatus,
    Transparency,
)


class TestCalendarEntry:
    def test_basic_creation(self):
        entry = CalendarEntry(
            summary="Meeting",
            start=datetime(2025, 7, 15, 10, 0),
            end=datetime(2025, 7, 15, 11, 0),
            start_tz="Europe/Berlin",
            end_tz="Europe/Berlin",
        )
        assert entry.summary == "Meeting"
        assert entry.start.tzinfo is not None
        assert entry.end.tzinfo is not None

    def test_aware_datetimes_accepted(self):
        entry = CalendarEntry(
            summary="Test",
            start=datetime(2025, 7, 15, 10, 0, tzinfo=ZoneInfo("Europe/Berlin")),
            end=datetime(2025, 7, 15, 11, 0, tzinfo=ZoneInfo("Europe/Berlin")),
            start_tz="Europe/Berlin",
            end_tz="Europe/Berlin",
        )
        assert entry.duration == timedelta(hours=1)

    def test_end_before_start_raises(self):
        with pytest.raises(ValueError, match="end must be after start"):
            CalendarEntry(
                summary="Bad",
                start=datetime(2025, 7, 15, 12, 0),
                end=datetime(2025, 7, 15, 10, 0),
                start_tz="UTC",
                end_tz="UTC",
            )

    def test_cross_timezone_duration(self):
        """Flight departing Berlin 14:00 CEST, arriving LA 17:00 PDT → 12 hours."""
        entry = CalendarEntry(
            summary="Flight",
            start=datetime(2025, 7, 15, 14, 0),
            end=datetime(2025, 7, 16, 2, 0),
            start_tz="Europe/Berlin",
            end_tz="America/Los_Angeles",
        )
        assert entry.duration == timedelta(hours=21)
        assert entry.start_local.hour == 14
        assert entry.end_local.hour == 2

    def test_duration_property(self):
        entry = CalendarEntry(
            summary="Test",
            start=datetime(2025, 7, 15, 10, 0),
            end=datetime(2025, 7, 15, 12, 30),
            start_tz="UTC",
            end_tz="UTC",
        )
        assert entry.duration == timedelta(hours=2, minutes=30)

    def test_uid_autogenerated(self):
        e1 = CalendarEntry(
            summary="A",
            start=datetime(2025, 1, 1, 0, 0),
            end=datetime(2025, 1, 1, 1, 0),
        )
        e2 = CalendarEntry(
            summary="B",
            start=datetime(2025, 1, 1, 0, 0),
            end=datetime(2025, 1, 1, 1, 0),
        )
        assert e1.uid != e2.uid
        assert e1.uid.endswith("@calendar-tz")

    def test_default_status(self):
        entry = CalendarEntry(
            summary="Test",
            start=datetime(2025, 1, 1, 0, 0),
            end=datetime(2025, 1, 1, 1, 0),
        )
        assert entry.status == EventStatus.CONFIRMED
        assert entry.transparency == Transparency.OPAQUE


class TestTravelCalendarEntry:
    def test_berlin_to_la_flight(self):
        entry = TravelCalendarEntry(
            summary="LH456 Berlin → Los Angeles",
            start=datetime(2025, 7, 15, 14, 0),
            end=datetime(2025, 7, 15, 17, 30),
            start_tz="Europe/Berlin",
            end_tz="America/Los_Angeles",
            departure_airport="BER",
            arrival_airport="LAX",
            departure_city="Berlin",
            arrival_city="Los Angeles",
            flight_number="LH456",
            airline="Lufthansa",
            booking_reference="ABC123",
        )
        assert "LH456" in entry.description
        assert "BER" in entry.description
        assert "LAX" in entry.description
        assert "ABC123" in entry.description
        assert entry.start_local.hour == 14

    def test_custom_description_not_overwritten(self):
        entry = TravelCalendarEntry(
            summary="Flight",
            start=datetime(2025, 7, 15, 14, 0),
            end=datetime(2025, 7, 15, 17, 30),
            start_tz="Europe/Berlin",
            end_tz="America/Los_Angeles",
            description="Custom notes",
        )
        assert entry.description == "Custom notes"
