"""Real flight data for the next 2 days (March 30-31, 2026).

Routes:
  - Frankfurt (FRA) → US destinations
  - LAX → Germany
  - LAX → Japan
"""

FLIGHTS = [
    # ── Frankfurt → US ─────────────────────────────────────────
    {
        "id": "lh456-mar30",
        "airline": "Lufthansa",
        "airline_code": "LH",
        "flight_number": "LH456",
        "aircraft": "Boeing 747-8",
        "departure_airport": "FRA",
        "departure_city": "Frankfurt",
        "departure_country": "Germany",
        "departure_tz": "Europe/Berlin",
        "departure_time": "2026-03-30T10:40",
        "arrival_airport": "LAX",
        "arrival_city": "Los Angeles",
        "arrival_country": "USA",
        "arrival_tz": "America/Los_Angeles",
        "arrival_time": "2026-03-30T13:10",
        "duration_hours": 11,
        "duration_minutes": 30,
        "route_group": "FRA → US",
    },
    {
        "id": "lh400-mar30",
        "airline": "Lufthansa",
        "airline_code": "LH",
        "flight_number": "LH400",
        "aircraft": "Airbus A340-600",
        "departure_airport": "FRA",
        "departure_city": "Frankfurt",
        "departure_country": "Germany",
        "departure_tz": "Europe/Berlin",
        "departure_time": "2026-03-30T11:00",
        "arrival_airport": "JFK",
        "arrival_city": "New York",
        "arrival_country": "USA",
        "arrival_tz": "America/New_York",
        "arrival_time": "2026-03-30T13:50",
        "duration_hours": 8,
        "duration_minutes": 50,
        "route_group": "FRA → US",
    },
    {
        "id": "lh430-mar30",
        "airline": "Lufthansa",
        "airline_code": "LH",
        "flight_number": "LH430",
        "aircraft": "Airbus A340-600",
        "departure_airport": "FRA",
        "departure_city": "Frankfurt",
        "departure_country": "Germany",
        "departure_tz": "Europe/Berlin",
        "departure_time": "2026-03-30T10:50",
        "arrival_airport": "ORD",
        "arrival_city": "Chicago",
        "arrival_country": "USA",
        "arrival_tz": "America/Chicago",
        "arrival_time": "2026-03-30T14:25",
        "duration_hours": 9,
        "duration_minutes": 35,
        "route_group": "FRA → US",
    },
    {
        "id": "ua927-mar30",
        "airline": "United Airlines",
        "airline_code": "UA",
        "flight_number": "UA927",
        "aircraft": "Boeing 787-10",
        "departure_airport": "FRA",
        "departure_city": "Frankfurt",
        "departure_country": "Germany",
        "departure_tz": "Europe/Berlin",
        "departure_time": "2026-03-30T17:25",
        "arrival_airport": "SFO",
        "arrival_city": "San Francisco",
        "arrival_country": "USA",
        "arrival_tz": "America/Los_Angeles",
        "arrival_time": "2026-03-30T20:10",
        "duration_hours": 11,
        "duration_minutes": 45,
        "route_group": "FRA → US",
    },
    {
        "id": "lh438-mar31",
        "airline": "Lufthansa",
        "airline_code": "LH",
        "flight_number": "LH438",
        "aircraft": "Airbus A330-300",
        "departure_airport": "FRA",
        "departure_city": "Frankfurt",
        "departure_country": "Germany",
        "departure_tz": "Europe/Berlin",
        "departure_time": "2026-03-31T10:10",
        "arrival_airport": "DFW",
        "arrival_city": "Dallas",
        "arrival_country": "USA",
        "arrival_tz": "America/Chicago",
        "arrival_time": "2026-03-31T14:25",
        "duration_hours": 11,
        "duration_minutes": 15,
        "route_group": "FRA → US",
    },
    # ── LAX → Germany ──────────────────────────────────────────
    {
        "id": "lh457-mar30",
        "airline": "Lufthansa",
        "airline_code": "LH",
        "flight_number": "LH457",
        "aircraft": "Boeing 747-8",
        "departure_airport": "LAX",
        "departure_city": "Los Angeles",
        "departure_country": "USA",
        "departure_tz": "America/Los_Angeles",
        "departure_time": "2026-03-30T15:00",
        "arrival_airport": "FRA",
        "arrival_city": "Frankfurt",
        "arrival_country": "Germany",
        "arrival_tz": "Europe/Berlin",
        "arrival_time": "2026-03-31T10:55",
        "duration_hours": 10,
        "duration_minutes": 55,
        "route_group": "LAX → Germany",
    },
    {
        "id": "lh453-mar30",
        "airline": "Lufthansa",
        "airline_code": "LH",
        "flight_number": "LH453",
        "aircraft": "Airbus A380",
        "departure_airport": "LAX",
        "departure_city": "Los Angeles",
        "departure_country": "USA",
        "departure_tz": "America/Los_Angeles",
        "departure_time": "2026-03-30T18:30",
        "arrival_airport": "MUC",
        "arrival_city": "Munich",
        "arrival_country": "Germany",
        "arrival_tz": "Europe/Berlin",
        "arrival_time": "2026-03-31T13:25",
        "duration_hours": 10,
        "duration_minutes": 55,
        "route_group": "LAX → Germany",
    },
    {
        "id": "lh457-mar31",
        "airline": "Lufthansa",
        "airline_code": "LH",
        "flight_number": "LH457",
        "aircraft": "Boeing 747-8",
        "departure_airport": "LAX",
        "departure_city": "Los Angeles",
        "departure_country": "USA",
        "departure_tz": "America/Los_Angeles",
        "departure_time": "2026-03-31T15:00",
        "arrival_airport": "FRA",
        "arrival_city": "Frankfurt",
        "arrival_country": "Germany",
        "arrival_tz": "Europe/Berlin",
        "arrival_time": "2026-04-01T10:55",
        "duration_hours": 10,
        "duration_minutes": 55,
        "route_group": "LAX → Germany",
    },
    # ── LAX → Japan ────────────────────────────────────────────
    {
        "id": "nh105-mar30",
        "airline": "ANA (All Nippon Airways)",
        "airline_code": "NH",
        "flight_number": "NH105",
        "aircraft": "Boeing 787-8",
        "departure_airport": "LAX",
        "departure_city": "Los Angeles",
        "departure_country": "USA",
        "departure_tz": "America/Los_Angeles",
        "departure_time": "2026-03-30T00:50",
        "arrival_airport": "HND",
        "arrival_city": "Tokyo (Haneda)",
        "arrival_country": "Japan",
        "arrival_tz": "Asia/Tokyo",
        "arrival_time": "2026-03-31T05:00",
        "duration_hours": 12,
        "duration_minutes": 10,
        "route_group": "LAX → Japan",
    },
    {
        "id": "jl15-mar30",
        "airline": "Japan Airlines",
        "airline_code": "JL",
        "flight_number": "JL15",
        "aircraft": "Boeing 777-300ER",
        "departure_airport": "LAX",
        "departure_city": "Los Angeles",
        "departure_country": "USA",
        "departure_tz": "America/Los_Angeles",
        "departure_time": "2026-03-30T12:30",
        "arrival_airport": "HND",
        "arrival_city": "Tokyo (Haneda)",
        "arrival_country": "Japan",
        "arrival_tz": "Asia/Tokyo",
        "arrival_time": "2026-03-31T17:30",
        "duration_hours": 12,
        "duration_minutes": 0,
        "route_group": "LAX → Japan",
    },
    {
        "id": "nh105-mar31",
        "airline": "ANA (All Nippon Airways)",
        "airline_code": "NH",
        "flight_number": "NH105",
        "aircraft": "Boeing 787-8",
        "departure_airport": "LAX",
        "departure_city": "Los Angeles",
        "departure_country": "USA",
        "departure_tz": "America/Los_Angeles",
        "departure_time": "2026-03-31T00:50",
        "arrival_airport": "HND",
        "arrival_city": "Tokyo (Haneda)",
        "arrival_country": "Japan",
        "arrival_tz": "Asia/Tokyo",
        "arrival_time": "2026-04-01T05:00",
        "duration_hours": 12,
        "duration_minutes": 10,
        "route_group": "LAX → Japan",
    },
]
